"""
MULTI_TENANT_DESIGN.md section 7 step 2: discard the demo rows, then add the
tenancy schema.

Two phases, deliberately separate commands rather than one run, because the
truncation has to be verified as a CHECKED FACT before the schema is touched —
not assumed to have happened because it was the plan:

    python3 scripts/migrate_add_tenancy.py --phase truncate   # then read the counts
    python3 scripts/migrate_add_tenancy.py --phase schema

The schema phase re-checks the counts itself and refuses to run against
non-empty tables, so the guard lives in code and not only in the operator's
memory of having run phase one.

What the schema phase does, per section 4:
  - CREATE tenants, tenant_settings
  - ALTER submissions / submission_rows ADD COLUMN tenant_id INTEGER NOT NULL
    REFERENCES tenants(id) — the PLAIN form. No DEFAULT <default_tenant_id>,
    no DROP DEFAULT, no default-tenant row. Those exist only to make backfill
    and NOT NULL atomic in one statement, and there is nothing to backfill
    against an empty table. Do not reintroduce them to make anything pass.
  - CREATE the two tenant indexes, and rebuild idx_rows_dedupe / idx_rows_route
    with tenant_id prepended, since a lookup index spanning tenants is itself a
    leak surface.

NOT here (step 3): _dedupe_hash() folding tenant_id into its key, the
persistence layer's required-tenant_id signatures, RLS policies, require_tenant.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

import review_queue

TABLES = ("submissions", "submission_rows")


def _counts(conn) -> dict:
    return {
        t: conn.execute(sql.SQL("SELECT COUNT(*) AS n FROM {}").format(sql.Identifier(t))).fetchone()["n"]
        for t in TABLES
    }


def phase_truncate(conn, schema: str) -> int:
    before = _counts(conn)
    print(f"before truncate: {before}")
    conn.execute("TRUNCATE submission_rows, submissions RESTART IDENTITY")
    conn.commit()
    after = _counts(conn)
    print(f"after truncate:  {after}")
    if any(after.values()):
        print("ERROR: truncation did not empty both tables — stopping before the schema changes.",
              file=sys.stderr)
        return 1
    print(f"VERIFIED: both tables are empty in schema '{schema}'.")
    return 0


def phase_schema(conn, schema: str) -> int:
    # The guard, in code rather than in the operator's memory: refuse to add a
    # NOT NULL column with no default to tables that still hold rows.
    counts = _counts(conn)
    if any(counts.values()):
        print(f"ERROR: {counts} — tables are not empty. Run --phase truncate first. "
              f"Refusing before touching the schema.", file=sys.stderr)
        return 1
    print(f"pre-flight row counts: {counts} — both empty, proceeding.")

    conn.execute("""
        CREATE TABLE IF NOT EXISTS tenants (
            id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug         TEXT UNIQUE NOT NULL,
            display_name TEXT NOT NULL,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS tenant_settings (
            tenant_id                INTEGER PRIMARY KEY REFERENCES tenants(id),
            hr_access_code_hash      TEXT NOT NULL,
            finance_access_code_hash TEXT NOT NULL,
            razorpayx_key_id         TEXT,
            razorpayx_key_secret     TEXT,
            razorpayx_account_number TEXT
        )
    """)

    existing = {
        (r["table_name"], r["column_name"])
        for r in conn.execute(
            "SELECT table_name, column_name FROM information_schema.columns "
            "WHERE table_schema = %s AND column_name = 'tenant_id'", (schema,)
        )
    }
    for table in TABLES:
        if (table, "tenant_id") in existing:
            print(f"{table}.tenant_id already present — skipping")
            continue
        conn.execute(sql.SQL(
            "ALTER TABLE {} ADD COLUMN tenant_id INTEGER NOT NULL REFERENCES tenants(id)"
        ).format(sql.Identifier(table)))
        print(f"{table}: added tenant_id INTEGER NOT NULL REFERENCES tenants(id)")

    conn.execute("CREATE INDEX IF NOT EXISTS idx_submissions_tenant ON submissions(tenant_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_rows_tenant ON submission_rows(tenant_id)")

    # Rebuilt, not merely supplemented: a dedupe/route lookup that spans tenants
    # is a leak surface in its own right (section 4).
    conn.execute("DROP INDEX IF EXISTS idx_rows_dedupe")
    conn.execute("DROP INDEX IF EXISTS idx_rows_route")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_rows_dedupe ON submission_rows(tenant_id, dedupe_hash)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_rows_route ON submission_rows(tenant_id, route)")
    conn.commit()
    print("indexes: idx_submissions_tenant, idx_rows_tenant created; "
          "idx_rows_dedupe / idx_rows_route rebuilt with tenant_id prepended")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", choices=("truncate", "schema"), required=True)
    ap.add_argument("--schema", default="public")
    args = ap.parse_args()

    review_queue.DB_SCHEMA = args.schema
    with psycopg.connect(review_queue._dsn(), row_factory=dict_row) as conn:
        conn.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(args.schema)))
        if args.phase == "truncate":
            return phase_truncate(conn, args.schema)
        return phase_schema(conn, args.schema)


if __name__ == "__main__":
    sys.exit(main())
